name: Build and Release

on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.14.0

    - name: Install Dependencies
      run: npm install

    - name: Build Electron App
      run: npm run make

    - name: Package Application
      run: npm run package
      
    - name: Upload Artifacts (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: out/make/squirrel.windows/x64/*.exe

    - name: Upload Artifacts (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: out/make/*.dmg

    - name: Upload Artifacts (Ubuntu Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: out/make/*.AppImage
